name: Arduino-cpp-test-action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COVERAGE_DATA_PATH: docs/arduino/coverage-data/coverage.info
    steps:
    - uses: actions/checkout@v2
    - uses: arduino/cpp-test-action@v1
      with:
        coverage-data-path: ${{ env.COVERAGE_DATA_PATH }}
    # Optional: upload coverage report to codecov.io
    #  - uses: codecov/codecov-action@v1
    #    with:
    #      file: ${{ env.COVERAGE_DATA_PATH }} # ex: extras/test/build/coverage.info
