name: Semantic-version

# Run the workflow when a Pull Request is opened or when changes are pushed to master
on:
 push:
  branches: [ main ]

jobs:
 release:
  # Only release on push to master
  if: github.event_name == 'push' && github.ref == 'refs/heads/master'
  runs-on: ubuntu-latest
  # Waits for test jobs to complete
  # needs: [test] // Removed as of now
  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Setup Node.js
    uses: actions/setup-node@v1
    with:
      node-version: 12.x

  - name: Install
    run: npm ci

  - name: Release
    run: npx semantic-release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
